name: release

on:
  create:
    tags: 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build
      run: cd tools/mc2bq && ./aux/build-all.sh

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Release Artifacts
      run: |
        set -x
        git fetch --tags
        cd tools/mc2bq && ./aux/release-artifacts.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

